name: Cypress

on:
  pull_request:
  push:
    branches:
      - main
      - stable*

env:
  APP_NAME: deck
  CYPRESS_baseUrl: http://localhost:8081/index.php

jobs:
  cypress:

    runs-on: ['ubuntu-latest', 'self-hosted']

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
        # containers: [1, 2, 3]
        php-versions: [ '8.1' ]
        server-versions: [ 'master' ]

    services:
      postgres:
        image: ghcr.io/nextcloud/continuous-integration-postgres-14:latest
        ports:
          - 4444:5432/tcp
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: rootpassword
          POSTGRES_DB: nextcloud
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Register text Git reference
        run: |
          text_app_ref="$(if [ "${{ matrix.server-versions }}" = "master" ]; then echo -n "main"; else echo -n "${{ matrix.server-versions }}"; fi)"
          echo "text_app_ref=$text_app_ref" >> $GITHUB_ENV

      - name: Checkout server
        uses: actions/checkout@v4.1.3
        with:
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Checkout ${{ env.APP_NAME }}
        uses: actions/checkout@v4.1.3
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Checkout text
        uses: actions/checkout@v4.1.3
        with:
          repository: nextcloud/text
          ref: ${{ env.text_app_ref }}
          path: apps/text

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@2.30.4
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, zip, gd, apcu
          ini-values:
            apc.enable_cli=on
          coverage: none

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
          PHP_CLI_SERVER_WORKERS: 5
        run: |
          mkdir data
          echo '<?php $CONFIG=["memcache.local"=>"\OC\Memcache\APCu","hashing_default_password"=>true];' > config/config.php
          php occ maintenance:install --verbose --database=pgsql --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
          php occ background:cron
          php -f index.php
          php -S 0.0.0.0:8081 &
          export OC_PASS=1234561
          php occ user:add --password-from-env user1
          php occ user:add --password-from-env user2
          php occ app:enable deck
          php occ app:list
          cd apps/deck
          composer install --no-dev
          npm ci
          npm run build
          curl -v http://localhost:8081/index.php/login

      - name: Run E2E cypress tests
        run: |
            cd 'apps/${{ env.APP_NAME }}'
            npx wait-on $CYPRESS_baseUrl
            npx cypress run --record false --config defaultCommandTimeout=10000,video=false
        env:
            # https://github.com/cypress-io/github-action/issues/124
            COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
            COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            npm_package_name: ${{ env.APP_NAME }}

      - name: Upload test failure screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Upload screenshots
          path: apps/${{ env.APP_NAME }}/cypress/screenshots/
          retention-days: 5

      - name: Upload nextcloud logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Upload nextcloud log
          path: data/nextcloud.log
          retention-days: 5
